module.exports = {
  CONN_STATUS_CODE: {
    CONN_OK: 'CONN_OK',
    CONN_REFUSED: 'CONN_REFUSED',
    CONN_TELNET_ERR: 'CONN_TELNET_ERR',
    CONN_PROXY_ERR: 'CONN_PROXY_ERR',
    CONN_CLOSED: 'CONN_CLOSED',
    CONN_CONTROL_MASKCHAR: 'CONN_CONTROL_MASKCHAR',
    CONN_CONTROL_UNMASKCHAR: 'CONN_CONTROL_UNMASKCHAR',
  },
  PROMPT_TRIGGER: '',
}